//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SpeechForms.Localization
{
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FilteringUIResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilteringUIResources()
        {
        }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeechForms.Localization.FilteringUIResources", typeof(FilteringUIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматическое скрытие.
        /// </summary>
        public static string Auto_hide
        {
            get
            {
                return ResourceManager.GetString("Auto_hide", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Состыковываемая панель.
        /// </summary>
        public static string Dockable
        {
            get
            {
                return ResourceManager.GetString("Dockable", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Активные документы.
        /// </summary>
        public static string Docking_ActiveDocuments
        {
            get
            {
                return ResourceManager.GetString("Docking_ActiveDocuments", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Активные панели.
        /// </summary>
        public static string Docking_ActivePanes
        {
            get
            {
                return ResourceManager.GetString("Docking_ActivePanes", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Предварительный просмотр.
        /// </summary>
        public static string Docking_PreviewHeader
        {
            get
            {
                return ResourceManager.GetString("Docking_PreviewHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Плавающая панель.
        /// </summary>
        public static string Floating
        {
            get
            {
                return ResourceManager.GetString("Floating", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить Фильтр.
        /// </summary>
        public static string GridViewClearFilter
        {
            get
            {
                return ResourceManager.GetString("GridViewClearFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        public static string GridViewFilter
        {
            get
            {
                return ResourceManager.GetString("GridViewFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на И.
        /// </summary>
        public static string GridViewFilterAnd
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterAnd", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Содержит.
        /// </summary>
        public static string GridViewFilterContains
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterContains", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на [Null].
        /// </summary>
        public static string GridViewFilterDistinctValueNull
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterDistinctValueNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на [пустая строка].
        /// </summary>
        public static string GridViewFilterDistinctValueStringEmpty
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterDistinctValueStringEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Не содержит.
        /// </summary>
        public static string GridViewFilterDoesNotContain
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterDoesNotContain", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Заканчивается на.
        /// </summary>
        public static string GridViewFilterEndsWith
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterEndsWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Содержится в.
        /// </summary>
        public static string GridViewFilterIsContainedIn
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsContainedIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Пусто.
        /// </summary>
        public static string GridViewFilterIsEmpty
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Равно.
        /// </summary>
        public static string GridViewFilterIsEqualTo
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string GridViewFilterIsFalse
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsFalse", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Больше, чем.
        /// </summary>
        public static string GridViewFilterIsGreaterThan
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsGreaterThan", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Больше или равно.
        /// </summary>
        public static string GridViewFilterIsGreaterThanOrEqualTo
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsGreaterThanOrEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Составляет менее.
        /// </summary>
        public static string GridViewFilterIsLessThan
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsLessThan", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Меньше или равно.
        /// </summary>
        public static string GridViewFilterIsLessThanOrEqualTo
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsLessThanOrEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Не содержится в.
        /// </summary>
        public static string GridViewFilterIsNotContainedIn
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsNotContainedIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Не является пустым.
        /// </summary>
        public static string GridViewFilterIsNotEmpty
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsNotEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Не равно.
        /// </summary>
        public static string GridViewFilterIsNotEqualTo
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsNotEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Не является null.
        /// </summary>
        public static string GridViewFilterIsNotNull
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsNotNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Равно null.
        /// </summary>
        public static string GridViewFilterIsNull
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string GridViewFilterIsTrue
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterIsTrue", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Учитывать регистр.
        /// </summary>
        public static string GridViewFilterMatchCase
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterMatchCase", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Или.
        /// </summary>
        public static string GridViewFilterOr
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterOr", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать Всё.
        /// </summary>
        public static string GridViewFilterSelectAll
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterSelectAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывать строки со значением, которое.
        /// </summary>
        public static string GridViewFilterShowRowsWithValueThat
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterShowRowsWithValueThat", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Начинается с.
        /// </summary>
        public static string GridViewFilterStartsWith
        {
            get
            {
                return ResourceManager.GetString("GridViewFilterStartsWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Перетащите сюда столбец для группировки.
        /// </summary>
        public static string GridViewGroupPanelText
        {
            get
            {
                return ResourceManager.GetString("GridViewGroupPanelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Сгруппировано по:.
        /// </summary>
        public static string GridViewGroupPanelTopTextGrouped
        {
            get
            {
                return ResourceManager.GetString("GridViewGroupPanelTopTextGrouped", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string GridViewSearchPanelTopText
        {
            get
            {
                return ResourceManager.GetString("GridViewSearchPanelTopText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрыть панель.
        /// </summary>
        public static string Hide
        {
            get
            {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимизировать панель.
        /// </summary>
        public static string RibbonBarQATMinimize
        {
            get
            {
                return ResourceManager.GetString("RibbonBarQATMinimize", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Развернуть панель.
        /// </summary>
        public static string RibbonViewExpandRibbon
        {
            get
            {
                return ResourceManager.GetString("RibbonViewExpandRibbon", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Больше.
        /// </summary>
        public static string RibbonViewGalleryButtonMore
        {
            get
            {
                return ResourceManager.GetString("RibbonViewGalleryButtonMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Строка.
        /// </summary>
        public static string RibbonViewGalleryButtonUpDown
        {
            get
            {
                return ResourceManager.GetString("RibbonViewGalleryButtonUpDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на от.
        /// </summary>
        public static string RibbonViewGalleryOfPart
        {
            get
            {
                return ResourceManager.GetString("RibbonViewGalleryOfPart", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        public static string RibbonViewHelp
        {
            get
            {
                return ResourceManager.GetString("RibbonViewHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Упрощенная лента.
        /// </summary>
        public static string RibbonViewLayoutModeButtonContent
        {
            get
            {
                return ResourceManager.GetString("RibbonViewLayoutModeButtonContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Свернуть панель.
        /// </summary>
        public static string RibbonViewMinimizeRibbon
        {
            get
            {
                return ResourceManager.GetString("RibbonViewMinimizeRibbon", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройка панели быстрого доступа.
        /// </summary>
        public static string RibbonViewQATCustomize
        {
            get
            {
                return ResourceManager.GetString("RibbonViewQATCustomize", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Сверните ленту.
        /// </summary>
        public static string RibbonViewQATMinimize
        {
            get
            {
                return ResourceManager.GetString("RibbonViewQATMinimize", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановите ленту.
        /// </summary>
        public static string RibbonViewQATRestore
        {
            get
            {
                return ResourceManager.GetString("RibbonViewQATRestore", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать над лентой.
        /// </summary>
        public static string RibbonViewQATShowAbove
        {
            get
            {
                return ResourceManager.GetString("RibbonViewQATShowAbove", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать под лентой.
        /// </summary>
        public static string RibbonViewQATShowBelow
        {
            get
            {
                return ResourceManager.GetString("RibbonViewQATShowBelow", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на -.
        /// </summary>
        public static string RibbonViewWindowTitleDivider
        {
            get
            {
                return ResourceManager.GetString("RibbonViewWindowTitleDivider", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        public static string RibbonWindowClose
        {
            get
            {
                return ResourceManager.GetString("RibbonWindowClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимизировать.
        /// </summary>
        public static string RibbonWindowMaximize
        {
            get
            {
                return ResourceManager.GetString("RibbonWindowMaximize", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимизировать.
        /// </summary>
        public static string RibbonWindowMinimize
        {
            get
            {
                return ResourceManager.GetString("RibbonWindowMinimize", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановить вниз.
        /// </summary>
        public static string RibbonWindowRestoreDown
        {
            get
            {
                return ResourceManager.GetString("RibbonWindowRestoreDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Документ с вкладками.
        /// </summary>
        public static string Tabbed_document
        {
            get
            {
                return ResourceManager.GetString("Tabbed_document", resourceCulture);
            }
        }
    }
}
